'use client';
import {useEffect,useMemo,useState} from 'react';
import {Plus,Wallet,Briefcase,User,Trash2,Pencil,Search,ChevronDown} from 'lucide-react';
import {money,parseAmount} from '../lib/amount';

const CATS={Personal:{'Alimentación':['Supermercado','Restaurante','Delivery','Cafetería','Otros'],'Hogar':['Servicios','Compras','Mantenimiento','Otros'],'Automóvil':['Combustible','Seguro','Patente','Mantenimiento','Otros'],'Salud':['Medicamentos','Consultas','Estudios','Otros'],'Familia':['Colegio','Ropa','Actividades','Otros'],'Ocio':['Suscripciones','Salidas','Entretenimiento','Otros'],'Otros':['Otros']},'Carpintería El Roble':{'Materiales':['Melamina','Madera','Herrajes','Otros'],'Herramientas':['Herramientas','Insumos','Mantenimiento','Otros'],'Movilidad':['Combustible','Fletes','Peajes','Otros'],'Servicios':['Servicios','Taller','Otros'],'Otros':['Otros']}};
const today=()=>new Date().toISOString().slice(0,10);
export default function Home(){
 const [expenses,setExpenses]=useState([]); const [form,setForm]=useState({date:today(),description:'',amount:'',scope:'Personal',category:'Alimentación',subcategory:'Supermercado',payment:'Efectivo'}); const [editing,setEditing]=useState(null); const [month,setMonth]=useState(today().slice(0,7)); const [filter,setFilter]=useState('Todos'); const [search,setSearch]=useState('');
 useEffect(()=>{try{setExpenses(JSON.parse(localStorage.getItem('gastos-v1')||'[]'))}catch{}},[]);
 useEffect(()=>{localStorage.setItem('gastos-v1',JSON.stringify(expenses))},[expenses]);
 const cats=Object.keys(CATS[form.scope]);
 useEffect(()=>{if(!CATS[form.scope][form.category])setForm(f=>({...f,category:Object.keys(CATS[f.scope])[0]}))},[form.scope]);
 useEffect(()=>{const subs=CATS[form.scope][form.category]||[]; if(!subs.includes(form.subcategory))setForm(f=>({...f,subcategory:subs[0]}))},[form.category,form.scope]);
 const filtered=useMemo(()=>expenses.filter(e=>e.date?.startsWith(month)&& (filter==='Todos'||e.scope===filter) && (!search||`${e.description} ${e.category} ${e.subcategory}`.toLowerCase().includes(search.toLowerCase()))).sort((a,b)=>b.date.localeCompare(a.date)),[expenses,month,filter,search]);
 const total=filtered.reduce((s,e)=>s+Number(e.amount),0); const personal=filtered.filter(e=>e.scope==='Personal').reduce((s,e)=>s+Number(e.amount),0); const business=filtered.filter(e=>e.scope==='Carpintería El Roble').reduce((s,e)=>s+Number(e.amount),0);
 const byCat=Object.entries(filtered.reduce((o,e)=>(o[e.category]=(o[e.category]||0)+Number(e.amount),o),{})).sort((a,b)=>b[1]-a[1]);
 function save(e){e.preventDefault(); const amount=parseAmount(form.amount); if(!form.description||!Number.isFinite(amount)||amount<=0)return; const item={...form,id:editing||crypto.randomUUID(),amount}; setExpenses(xs=>editing?xs.map(x=>x.id===editing?item:x):[item,...xs]); setEditing(null);setForm(f=>({...f,description:'',amount:'',date:today()}));}
 function edit(x){setEditing(x.id);setForm(x)} function del(id){if(confirm('¿Eliminar este gasto?'))setExpenses(xs=>xs.filter(x=>x.id!==id))}
 return <main><header><div><span className="eyebrow">CONTROL DE GASTOS · V1</span><h1>Mis gastos</h1><p>Registro simple. Análisis después.</p></div><div className="month"><label>Mes</label><input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></div></header>
 <section className="hero"><div><span>Gasto del mes</span><strong>{money(total)}</strong></div><div><span>Personal</span><b>{money(personal)}</b></div><div><span>Carpintería</span><b>{money(business)}</b></div></section>
 <section className="grid"><form className="card form" onSubmit={save}><div className="cardtitle"><div><span className="eyebrow">NUEVO MOVIMIENTO</span><h2>{editing?'Editar gasto':'Agregar gasto'}</h2></div><Wallet size={22}/></div><label>Importe<input inputMode="decimal" placeholder="$ 0" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></label><label>Descripción<input placeholder="Ej. supermercado" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><div className="two"><label>Fecha<input type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></label><label>Ámbito<select value={form.scope} onChange={e=>setForm({...form,scope:e.target.value,category:Object.keys(CATS[e.target.value])[0]})}><option>Personal</option><option>Carpintería El Roble</option></select></label></div><div className="two"><label>Categoría<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{cats.map(x=><option key={x}>{x}</option>)}</select></label><label>Subcategoría<select value={form.subcategory} onChange={e=>setForm({...form,subcategory:e.target.value})}>{(CATS[form.scope][form.category]||[]).map(x=><option key={x}>{x}</option>)}</select></label></div><label>Medio de pago<select value={form.payment} onChange={e=>setForm({...form,payment:e.target.value})}><option>Efectivo</option><option>Débito</option><option>Crédito</option><option>Transferencia</option><option>Otro</option></select></label><button className="primary"><Plus size={18}/>{editing?'Guardar cambios':'Registrar gasto'}</button>{editing&&<button type="button" className="secondary" onClick={()=>{setEditing(null);setForm({...form,description:'',amount:''})}}>Cancelar</button>}</form>
 <div className="card history"><div className="cardtitle"><div><span className="eyebrow">HISTORIAL</span><h2>Movimientos</h2></div><span className="count">{filtered.length}</span></div><div className="toolbar"><div className="search"><Search size={16}/><input placeholder="Buscar" value={search} onChange={e=>setSearch(e.target.value)}/></div><select value={filter} onChange={e=>setFilter(e.target.value)}><option>Todos</option><option>Personal</option><option>Carpintería El Roble</option></select></div>{filtered.length===0?<div className="empty">Todavía no hay gastos para este mes.</div>:<div className="list">{filtered.map(x=><article key={x.id}><div className="icon">{x.scope==='Personal'?<User size={17}/>:<Briefcase size={17}/>}</div><div className="desc"><b>{x.description}</b><small>{new Date(x.date+'T12:00:00').toLocaleDateString('es-AR')} · {x.category} / {x.subcategory} · {x.payment}</small></div><strong>{money(x.amount)}</strong><button className="iconbtn" onClick={()=>edit(x)} aria-label="Editar"><Pencil size={15}/></button><button className="iconbtn danger" onClick={()=>del(x.id)} aria-label="Eliminar"><Trash2 size={15}/></button></article>)}</div>}</div></section>
 <section className="card categories"><div className="cardtitle"><div><span className="eyebrow">PREVISUALIZACIÓN</span><h2>Por categoría</h2></div></div>{byCat.length===0?<div className="empty">Los totales aparecerán cuando registres gastos.</div>:byCat.map(([c,v])=><div className="barrow" key={c}><div><span>{c}</span><b>{money(v)}</b></div><div className="bar"><i style={{width:`${Math.max(4,(v/byCat[0][1])*100)}%`}}/></div></div>)}</section>
 <footer>V1 · Los datos se guardan localmente en este dispositivo. La sincronización y la importación con IA se incorporarán en las siguientes versiones.</footer></main>
}
